// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv";
import { fileURLToPath } from "url";
import { dirname, join } from "path";
import { defineConfig, env } from "prisma/config";
import fs from "fs";

// Helper function to write debug logs
function writeDebugLog(data) {
  try {
    // Calculate workspace root from process.cwd() - when run from backend/, go up one level
    const cwd = process.cwd();
    const workspaceRoot = cwd.endsWith('backend') ? join(cwd, '..') : cwd;
    const logPath = join(workspaceRoot, '.cursor', 'debug.log');
    // Ensure .cursor directory exists
    const logDir = join(workspaceRoot, '.cursor');
    if (!fs.existsSync(logDir)) {
      fs.mkdirSync(logDir, { recursive: true });
    }
    const logEntry = JSON.stringify({ ...data, timestamp: Date.now() }) + '\n';
    fs.appendFileSync(logPath, logEntry, 'utf8');
  } catch (e) {
    // Ignore log errors
  }
}

// #region agent log - Module entry point
try {
  const cwd = process.cwd();
  const workspaceRoot = cwd.endsWith('backend') ? join(cwd, '..') : cwd;
  const logPath = join(workspaceRoot, '.cursor', 'debug.log');
  const logDir = join(workspaceRoot, '.cursor');
  if (!fs.existsSync(logDir)) {
    fs.mkdirSync(logDir, { recursive: true });
  }
  fs.appendFileSync(logPath, JSON.stringify({
    sessionId: "debug-session",
    runId: "run1",
    hypothesisId: "H0",
    location: "backend/prisma.config.ts:28",
    message: "Prisma config module STARTED",
    data: { nodeVersion: process.version, cwd },
    timestamp: Date.now(),
  }) + '\n', 'utf8');
} catch (e) {}
// #endregion

// Load root .env to match backend runtime config (backend/src/config/database.js).
// This avoids differences between Prisma CLI (run from ./backend) and the app env loading.
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const envPath = join(__dirname, "../.env");

// #region agent log
writeDebugLog({
  sessionId: "debug-session",
  runId: "run1",
  hypothesisId: "H1",
  location: "backend/prisma.config.ts:47",
  message: "Env file path before dotenv.config",
  data: {
    __dirname,
    envPath,
    cwd: process.cwd(),
  },
});
// #endregion

const envFileExists = fs.existsSync(envPath);

// #region agent log
writeDebugLog({
  sessionId: "debug-session",
  runId: "run1",
  hypothesisId: "H1",
  location: "backend/prisma.config.ts:71",
  message: "Env file existence check",
  data: {
    envFileExists,
    envPath,
  },
});
// #endregion

const dotenvResult = dotenv.config({ path: envPath });

// #region agent log
writeDebugLog({
  sessionId: "debug-session",
  runId: "run1",
  hypothesisId: "H3",
  location: "backend/prisma.config.ts:88",
  message: "dotenv.config result",
  data: {
    hasError: !!dotenvResult.error,
    errorMessage: dotenvResult.error?.message || null,
    parsedKeysCount: dotenvResult.parsed ? Object.keys(dotenvResult.parsed).length : 0,
    hasDatabaseUrlInParsed: dotenvResult.parsed ? 'DATABASE_URL' in dotenvResult.parsed : false,
  },
});
// #endregion

// #region agent log
writeDebugLog({
  sessionId: "debug-session",
  runId: "run1",
  hypothesisId: "H4",
  location: "backend/prisma.config.ts:109",
  message: "process.env.DATABASE_URL before env() call",
  data: {
    hasDatabaseUrl: !!process.env.DATABASE_URL,
    databaseUrlLength: process.env.DATABASE_URL?.length ?? 0,
    databaseUrlPrefix: process.env.DATABASE_URL ? String(process.env.DATABASE_URL).slice(0, 20) : null,
  },
});
// #endregion

// Use process.env directly (same as database.js) instead of env() which throws if missing
const dbUrl = process.env.DATABASE_URL;

// #region agent log
writeDebugLog({
  sessionId: "debug-session",
  runId: "run1",
  hypothesisId: "H5",
  location: "backend/prisma.config.ts:121",
  message: "Using process.env.DATABASE_URL",
  data: {
    hasDatabaseUrl: !!dbUrl,
    databaseUrlLength: dbUrl?.length ?? 0,
    databaseUrlPrefix: dbUrl ? String(dbUrl).slice(0, 20) : null,
  },
});
// #endregion

if (!dbUrl) {
  throw new Error('Missing required environment variable: DATABASE_URL. Make sure .env file exists in the project root and contains DATABASE_URL.');
}

// #region agent log
try {
  typeof fetch === "function" &&
    fetch("http://127.0.0.1:7243/ingest/46d63257-3d3d-4b19-b340-327acd66351f", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        sessionId: "debug-session",
        runId: "pre-fix",
        hypothesisId: "H3",
        location: "backend/prisma.config.ts:30",
        message: "DATABASE_URL presence (masked)",
        data: {
          hasDatabaseUrl: Boolean(dbUrl),
          databaseUrlLength: dbUrl?.length ?? 0,
          databaseUrlPrefix: dbUrl ? String(dbUrl).slice(0, 20) : null,
        },
        timestamp: Date.now(),
      }),
    }).catch(() => {});
} catch {}
// #endregion

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    provider: "sqlserver",
    url: dbUrl,
  },
});

// #region agent log
try {
  typeof fetch === "function" &&
    fetch("http://127.0.0.1:7243/ingest/46d63257-3d3d-4b19-b340-327acd66351f", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        sessionId: "debug-session",
        runId: "pre-fix",
        hypothesisId: "H2",
        location: "backend/prisma.config.ts:53",
        message: "Prisma config exported",
        data: { schemaPath: "prisma/schema.prisma", migrationsPath: "prisma/migrations", provider: "sqlserver" },
        timestamp: Date.now(),
      }),
    }).catch(() => {});
} catch {}
// #endregion
